# Generated by Django 3.2.8 on 2021-10-24 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0002_auto_20211024_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soccer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='tunr.soccer')),
            ],
        ),
    ]
