# Generated by Django 3.2.8 on 2021-10-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='draws',
            field=models.CharField(default='empty value', max_length=100),
        ),
        migrations.AddField(
            model_name='statistic',
            name='losses',
            field=models.CharField(default='empty value', max_length=100),
        ),
        migrations.AddField(
            model_name='statistic',
            name='name',
            field=models.CharField(default='no name ', max_length=100),
        ),
        migrations.AddField(
            model_name='statistic',
            name='preview_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statistic',
            name='wins',
            field=models.CharField(default='empty value', max_length=100),
        ),
        migrations.AlterField(
            model_name='soccer',
            name='photo_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
