# Generated by Django 3.2.8 on 2021-10-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0004_auto_20211024_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soccer',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='soccer',
            name='team',
        ),
        migrations.AddField(
            model_name='soccer',
            name='age',
            field=models.CharField(default='no value', max_length=100),
        ),
        migrations.AddField(
            model_name='soccer',
            name='ast',
            field=models.CharField(default='no value', max_length=100),
        ),
        migrations.AddField(
            model_name='soccer',
            name='gls',
            field=models.CharField(default='no value', max_length=100),
        ),
        migrations.AddField(
            model_name='soccer',
            name='minutes',
            field=models.CharField(default='no value', max_length=100),
        ),
        migrations.AddField(
            model_name='soccer',
            name='mp',
            field=models.CharField(default='no value', max_length=100),
        ),
        migrations.AddField(
            model_name='soccer',
            name='nineties',
            field=models.CharField(default='no value', max_length=100),
        ),
        migrations.AddField(
            model_name='soccer',
            name='poss',
            field=models.CharField(default='no value', max_length=100),
        ),
        migrations.AddField(
            model_name='soccer',
            name='squad',
            field=models.CharField(default='no value', max_length=100),
        ),
        migrations.AddField(
            model_name='soccer',
            name='starts',
            field=models.CharField(default='no value', max_length=100),
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
