# Generated by Django 3.2.8 on 2021-10-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0005_auto_20211024_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soccer',
        ),
    ]
