# Generated by Django 3.2.8 on 2021-10-24 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soccer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.CharField(default='no value', max_length=100)),
                ('age', models.CharField(default='no value', max_length=100)),
                ('poss', models.CharField(default='no value', max_length=100)),
                ('mp', models.CharField(default='no value', max_length=100)),
                ('starts', models.CharField(default='no value', max_length=100)),
                ('minutes', models.CharField(default='no value', max_length=100)),
                ('nineties', models.CharField(default='no value', max_length=100)),
                ('gls', models.CharField(default='no value', max_length=100)),
                ('ast', models.CharField(default='no value', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soccer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='soccer.soccer')),
            ],
        ),
    ]
